<?php
/**
 * @file
 * hey_babies.features.menu_custom.inc
 */

/**
 * Implements hook_menu_default_menu_custom().
 */
function hey_babies_menu_default_menu_custom() {
  $menus = array();

  // Exported menu: main-menu.
  $menus['main-menu'] = array(
    'menu_name' => 'main-menu',
    'title' => 'Main menu',
    'description' => 'The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.',
  );
  // Exported menu: menu-footer-bottom-menu.
  $menus['menu-footer-bottom-menu'] = array(
    'menu_name' => 'menu-footer-bottom-menu',
    'title' => 'Footer bottom menu',
    'description' => '',
  );
  // Exported menu: menu-footer-menu.
  $menus['menu-footer-menu'] = array(
    'menu_name' => 'menu-footer-menu',
    'title' => 'Footer menu',
    'description' => '',
  );
  // Exported menu: menu-footer-social-menu.
  $menus['menu-footer-social-menu'] = array(
    'menu_name' => 'menu-footer-social-menu',
    'title' => 'Footer social menu',
    'description' => '',
  );
  // Exported menu: user-menu.
  $menus['user-menu'] = array(
    'menu_name' => 'user-menu',
    'title' => 'User menu',
    'description' => 'The <em>User</em> menu contains links related to the user\'s account, as well as the \'Log out\' link.',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Footer bottom menu');
  t('Footer menu');
  t('Footer social menu');
  t('Main menu');
  t('The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.');
  t('The <em>User</em> menu contains links related to the user\'s account, as well as the \'Log out\' link.');
  t('User menu');

  return $menus;
}
