<?php
function hb_size_filter_views_pre_view(&$view, &$display_id, &$args)
{
    if ($view->name == 'products')
    {
        if (empty($view->exposed_input))
        {
            $view->exposed_input = array();
        }
        if (isset($_COOKIE['SESSsize']))
        {
            $sizes = explode('+', $_COOKIE['SESSsize']);
            $view->exposed_input['size'] = $sizes;
        }
    }
}
